x-debug-env: &debug-env
  CRYPTNA_DEBUG: ${CRYPTNA_DEBUG:-0}

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: cryptna-client
    command: sleep infinity
    networks:
      control_net:
        ipv4_address: 172.20.0.10
      data_net:
        ipv4_address: 172.21.0.10
    environment:
      <<: *debug-env

  pdp:
    build:
      context: .
      dockerfile: pdp/Dockerfile
    container_name: cryptna-pdp
    networks:
      control_net:
        ipv4_address: 172.20.0.20
    environment:
      <<: *debug-env

  pip:
    build:
      context: .
      dockerfile: pip/Dockerfile
    container_name: cryptna-pip
    volumes:
      - pip_data:/data
    networks:
      control_net:
        ipv4_address: 172.20.0.30
    environment:
      <<: *debug-env

  pep:
    build:
      context: .
      dockerfile: pep/Dockerfile
    container_name: cryptna-pep
    networks:
      control_net:
        ipv4_address: 172.20.0.40
      data_net:
        ipv4_address: 172.21.0.40
      service_net:
        ipv4_address: 172.22.0.40
    environment:
      <<: *debug-env

  service-http:
    image: nginx:alpine
    container_name: cryptna-service-http
    networks:
      service_net:
        ipv4_address: 172.22.0.50

networks:
  control_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
  data_net:
    ipam:
      config:
        - subnet: 172.21.0.0/24
  service_net:
    ipam:
      config:
        - subnet: 172.22.0.0/24

volumes:
  pip_data:
