services:
  client:
    build: ./client
    container_name: cryptna-client
    command: sleep infinity
    networks:
      control_net:
        ipv4_address: 172.20.0.10
      data_net:
        ipv4_address: 172.21.0.10

  pdp:
    build: ./pdp
    container_name: cryptna-pdp
    command: sleep infinity
    networks:
      control_net:
        ipv4_address: 172.20.0.20

  pip:
    build: ./pip
    container_name: cryptna-pip
    volumes:
      - pip_data:/data
    networks:
      control_net:
        ipv4_address: 172.20.0.30

  pep:
    build: ./pep
    container_name: cryptna-pep
    command: sleep infinity
    networks:
      control_net:
        ipv4_address: 172.20.0.40
      data_net:
        ipv4_address: 172.21.0.40
      service_net:
        ipv4_address: 172.22.0.40

  service-http:
    image: nginx:alpine
    container_name: cryptna-service-http
    networks:
      service_net:
        ipv4_address: 172.22.0.50

networks:
  control_net:
    ipam:
      config:
        - subnet: 172.20.0.0/24
  data_net:
    ipam:
      config:
        - subnet: 172.21.0.0/24
  service_net:
    ipam:
      config:
        - subnet: 172.22.0.0/24

volumes:
  pip_data:
